from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(522, 289)
        self.line_name = QtWidgets.QLineEdit(Form)
        self.line_name.setGeometry(QtCore.QRect(160, 50, 351, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_name.setFont(font)
        self.line_name.setObjectName("line_name")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 501, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_name = QtWidgets.QLabel(Form)
        self.label_name.setGeometry(QtCore.QRect(10, 50, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_name.setFont(font)
        self.label_name.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_name.setObjectName("label_name")
        self.label_degrees = QtWidgets.QLabel(Form)
        self.label_degrees.setGeometry(QtCore.QRect(10, 90, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_degrees.setFont(font)
        self.label_degrees.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_degrees.setObjectName("label_degrees")
        self.box_degrees = QtWidgets.QComboBox(Form)
        self.box_degrees.setGeometry(QtCore.QRect(160, 90, 351, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.box_degrees.setFont(font)
        self.box_degrees.setObjectName("box_degrees")
        self.box_degrees.addItem("")
        self.box_degrees.addItem("")
        self.box_degrees.addItem("")
        self.box_degrees.addItem("")
        self.label_griding = QtWidgets.QLabel(Form)
        self.label_griding.setGeometry(QtCore.QRect(10, 130, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_griding.setFont(font)
        self.label_griding.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_griding.setObjectName("label_griding")
        self.box_griding = QtWidgets.QComboBox(Form)
        self.box_griding.setGeometry(QtCore.QRect(160, 130, 351, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.box_griding.setFont(font)
        self.box_griding.setObjectName("box_griding")
        self.box_griding.addItem("")
        self.box_griding.addItem("")
        self.box_griding.addItem("")
        self.box_quality = QtWidgets.QComboBox(Form)
        self.box_quality.setGeometry(QtCore.QRect(160, 170, 351, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.box_quality.setFont(font)
        self.box_quality.setObjectName("box_quality")
        self.box_quality.addItem("")
        self.box_quality.addItem("")
        self.box_quality.addItem("")
        self.box_quality.addItem("")
        self.label_quality = QtWidgets.QLabel(Form)
        self.label_quality.setGeometry(QtCore.QRect(10, 170, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_quality.setFont(font)
        self.label_quality.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_quality.setObjectName("label_quality")
        self.line_price = QtWidgets.QLineEdit(Form)
        self.line_price.setGeometry(QtCore.QRect(160, 210, 351, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_price.setFont(font)
        self.line_price.setText("")
        self.line_price.setObjectName("line_price")
        self.label_price = QtWidgets.QLabel(Form)
        self.label_price.setGeometry(QtCore.QRect(10, 210, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_price.setFont(font)
        self.label_price.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_price.setObjectName("label_price")
        self.btn = QtWidgets.QPushButton(Form)
        self.btn.setGeometry(QtCore.QRect(10, 250, 501, 25))
        self.btn.setObjectName("btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Редактирование или добавление в базу данных"))
        self.label_name.setText(_translate("Form", "Имя"))
        self.label_degrees.setText(_translate("Form", "Обжарка"))
        self.box_degrees.setItemText(0, _translate("Form", "высшая"))
        self.box_degrees.setItemText(1, _translate("Form", "сильная"))
        self.box_degrees.setItemText(2, _translate("Form", "средняя"))
        self.box_degrees.setItemText(3, _translate("Form", "легкая"))
        self.label_griding.setText(_translate("Form", "Помол"))
        self.box_griding.setItemText(0, _translate("Form", "крупный"))
        self.box_griding.setItemText(1, _translate("Form", "средний"))
        self.box_griding.setItemText(2, _translate("Form", "мелкий"))
        self.box_quality.setItemText(0, _translate("Form", "низкое"))
        self.box_quality.setItemText(1, _translate("Form", "среднее"))
        self.box_quality.setItemText(2, _translate("Form", "хорошее"))
        self.box_quality.setItemText(3, _translate("Form", "лучшее"))
        self.label_quality.setText(_translate("Form", "Качество"))
        self.label_price.setText(_translate("Form", "Цена"))
        self.btn.setText(_translate("Form", "PUSH"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
